### ISSUE TITLE
serialize-form

### ISSUE THREAD

**Issue by ianstormtaylor** [yields/serialize#1]
seems like it would make more sense for a `serialize-form` component that serializes the form into a regular object, and then use `querystring` to url encode it? seems more flexible. or at least i could see myself depending on a serializer to `object` a lot more than straight to url encoded string, which is a smaller use case

just food for thought. feel free to close this

**Comment by yields** [comment]
yeah haha, i realized this isn't flexible as well, i'm going to add `.object()` soon :)

**Comment by yields** [comment]
999e752b00e91cbbcc6dc911ff564726c29f67dd :)

**Comment by ianstormtaylor** [comment]
nice! :)
