### ISSUE TITLE
querystring doesn't handle arrays very well

### ISSUE THREAD

**Issue by eivindfjeldstad** [yields/serialize#3]
[component/querystring](https://github.com/component/querystring) can't handle arrays properly.

``` js
qs.stringify({ 'array[]': [1, 2, 3] });
// => array[]=1,2,3
```

Would you consider switching to another qs library?
[visionmedia/node-querystring](https://github.com/visionmedia/node-querystring)
or
[anchorjs/querystring](https://github.com/anchorjs/querystring)

**Comment by yields** [comment]
what's the use case ?

only asking since you can't feed any objects to `serialize()` or `.object()` only form elements.

**Comment by eivindfjeldstad** [comment]
Let's say you have a form like this:

``` html
<input name='array[]' value='1'>
<input name='array[]' value='2'>
```

and do

``` js
serialize(form);
//=> array[]=1,2
```

Expected result in this case would be `array[]=1&array[]=2`

**Comment by yields** [comment]
added some more tests including `array[]`.

db8d3554c8f8abf23dba6a0f3e8a9b8f8e703497 thanks.

**Comment by eivindfjeldstad** [comment]
sweet, thanks!
