### ISSUE TITLE
feature: handle arbitrary containers, not just forms

### ISSUE THREAD

**Issue by stephenmathieson** [yields/serialize#4]
not sure if you'd be cool with this (hence the issue, not a pr ;)), but i'd like to be able to do something like this:

``` js
var serialize = require('serialize')
// ...

function MyView() {
  // ...
  this.events.bind('submit form', 'onsubmit')
}

MyView.prototype.onsubmit = function () {
  // key line here:
  this.doSomething(serialize(this.el))
}
```

rather than:

``` js
MyView.prototype.onsubmit = function () {
  // key line here:
  this.doSomething(serialize(this.el.querySelector('form')))
}
```

also, what if `MyView` doesn't contain an actual `<form />`, but just some inputs instead?

**Comment by yields** [comment]
Interesting, 

the reason `<form>`s are supported is because they have this `.elements`  that contains all `inputs` even nested ones.

i'm fine with supporting array of inputs too, since the function supports `.elements` you can simply do something like (not elegant but still):

``` js
function MyView(){
  this.elements = this.el.querySelectorAll('input');
}

MyView.prototype.onsubmit = function(e){
  this.doSomething(serialize(this));
};
```

**Comment by stephenmathieson** [comment]
hmm yeah that could work.  it's kinda ugly though haha.

regarding `.elements`: because it's already `reduce`-ing elements, why not just

``` js
 var ret = reduce(el.getElementsByTagName('*'), param, []);
 return ret.join('&').replace(/%20/g, '+');
```

**EDIT**: may need more than `el.getElementsByTagName` for ie

**Comment by yields** [comment]
+1 to your solution, we can also use `component/query` and then just let people who care about ie add their own engines.

**Comment by stephenmathieson** [comment]
ok, cool.  i'll fork and add support in a bit.
